kind: "BuildConfig"
apiVersion: "v1"
metadata:
        name: "build-pipeline"
spec:
        strategy:
                jenkinsPipelineStrategy:
                        jenkinsfile:
                type: JenkinsPipeline
