apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata: 
  name: build-trigger-b
spec:
  params:
  - name: URL
    value: $(body.repository.clone_url)
  - name: REVISION
    value: $(body.pull_request.head.sha)
  - name: NAMESPACE
    value: spring-mvc
  - name: SERVICE_ACCOUNT
    value: trigger