apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: event-listener
  name: el-route
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-route