apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-triggers
spec:
  # params:
  # - name: URL
  #   description: http://ec2-3-96-94-51.ca-central-1.compute.amazonaws.com:3000/andrewnguyen/Spring_MVC_Gitea.Spring_MVC_Gitea.git
  # - name: REVISION
  #   description: master
  # - name: NAMESPACE
  #   description: spring-mvc
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-run-from-trigger
    spec:
      pipelineRef:
        name: new-pipeline
      resources:
      - name: app-git
        resourceRef:
          name: source-git
      - name: app-image
        resourceRef:
          name: app-image
