apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: http://ec2-3-96-94-51.ca-central-1.compute.amazonaws.com:3000/andrewnguyen/Spring_MVC_Gitea.git